// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDutfHXYWmwjra9Mmk5Dqd7515sglEeQZg',
    appId: '1:86285315023:web:edc08570ae9826a081c0ba',
    messagingSenderId: '86285315023',
    projectId: 'vaagai-5cb27',
    authDomain: 'vaagai-5cb27.firebaseapp.com',
    storageBucket: 'vaagai-5cb27.firebasestorage.app',
    measurementId: 'G-4BJFT7PGCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI5loe0GYXCygF8wqqCA2vBpSFyb5aknE',
    appId: '1:86285315023:android:d3531f57b68fc19d81c0ba',
    messagingSenderId: '86285315023',
    projectId: 'vaagai-5cb27',
    storageBucket: 'vaagai-5cb27.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDutfHXYWmwjra9Mmk5Dqd7515sglEeQZg',
    appId: '1:86285315023:web:db54c4dc86acce4a81c0ba',
    messagingSenderId: '86285315023',
    projectId: 'vaagai-5cb27',
    authDomain: 'vaagai-5cb27.firebaseapp.com',
    storageBucket: 'vaagai-5cb27.firebasestorage.app',
    measurementId: 'G-FL1SVF6C73',
  );

}